spring.application.name=onlinebanking
server.port=8090
spring.datasource.url=jdbc:mysql://localhost:3306/online_bank

spring.datasource.username=root
spring.datasource.password=root1234

spring.security.user.name=admin
spring.security.user.password=password123

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect